# Generated by Django 5.2 on 2025-04-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='llmmodel',
            name='api_key',
        ),
        migrations.AddField(
            model_name='llmagent',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
