# Generated by Django 5.2 on 2025-05-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0002_remove_llmmodel_api_key_llmagent_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='exercise_file',
            field=models.FileField(default=None, upload_to='exercises/'),
        ),
        migrations.AddField(
            model_name='task',
            name='prog_lang',
            field=models.CharField(default='C', max_length=25),
        ),
        migrations.AddField(
            model_name='task',
            name='rubric_file',
            field=models.FileField(default=None, upload_to='rubrics/'),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='theme',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
