# Generated by Django 5.2 on 2025-06-15 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0005_taskresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='state',
        ),
        migrations.AddField(
            model_name='task',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En proceso'), ('SUCCESS', 'Completado'), ('ERROR', 'Error')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='exercise_file',
            field=models.FileField(upload_to='exercises/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='rubric_file',
            field=models.FileField(upload_to='rubrics/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='theme',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
